E-mailSystem/Controllers/EmailController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using E_mailSystem.Services;
using E_mailSystem.Models;
using E_mailSystem.Data;

using E_mailSystem.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace E_mailSystem.Controllers
{
    public class EmailController : Controller
    {
        private readonly ApplicationDbContext _context;
        

        public EmailController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            try
            {
                var UserP = _context.Users.FirstOrDefault(uid => uid.UserName == User.Identity.Name);
                var Plan = _context.Plans.FirstOrDefault(pid => pid.Id == UserP.PlanId) as Plan;

                var Info = new PlanInfoVM()
                {
                    PlanName = Plan.PlanName,
                    MessagesLeft = Plan.Messages - UserP.MessagesSent

                };

                ViewData["PlanInfoVm"] = Info;
            }
            catch(Exception err)
            {

            }
           
            return View();
        }

        public IActionResult MessageSended()
        {
            return View();
        }

        public async Task<IActionResult> SendMessage1(string to, string subject, string body )
        {
            
            EmailService emailService = new EmailService();
            await emailService.SendEmailAsync(to, subject, body);
            

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult SendMessage(MessageModel model)
        {
            if (ModelState.IsValid)
            {
                SendMessage1(model.ToEmail, model.Subject, model.Body);
                //var ThisUser =  _context.Users
                //.FirstOrDefault(m => m.UserName == User.Identity.Name);
                
                
                //_context.Users.Update(ThisUser);
                //_context.SaveChanges();
                
            }

            return View("MessageSended", model);
        }
    }
}

E-mailSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bibbo - your best Mail</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bibbo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" style="color:cornflowerblue">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Пользовательское соглашение</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Plans">Тарифы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Email" asp-action="Index">Email</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.Identity.Name == "admin123@gmail.com")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Plans" asp-action="Index">Plans</a>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Bibbo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Пользовательское соглашение</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>